#!/bin/bash

## Copyright (C) 2012 - 2018 Patrick Schleizer <adrelanos@riseup.net>
## See the file COPYING for copying conditions.

#set -x

output_identifier="$$"
export output_identifier

if [ "$(id -u)" != "0" ]; then
   echo "($output_identifier) ERROR: This must be run as root (sudo)!"
   exit 1
else
   true "($output_identifier) INFO: Script running as root."
fi

colors() {
   if [ "$TERM" = "" ]; then
      return 0
   fi

   ## Thanks to:
   ## http://mywiki.wooledge.org/BashFAQ/037
   ## Variables for terminal requests.
   [[ -t 2 ]] && {
       alt=$(      tput smcup  || tput ti      ) # Start alt display
       ealt=$(     tput rmcup  || tput te      ) # End   alt display
       hide=$(     tput civis  || tput vi      ) # Hide cursor
       show=$(     tput cnorm  || tput ve      ) # Show cursor
       save=$(     tput sc                     ) # Save cursor
       load=$(     tput rc                     ) # Load cursor
       bold=$(     tput bold   || tput md      ) # Start bold
       stout=$(    tput smso   || tput so      ) # Start stand-out
       estout=$(   tput rmso   || tput se      ) # End stand-out
       under=$(    tput smul   || tput us      ) # Start underline
       eunder=$(   tput rmul   || tput ue      ) # End   underline
       reset=$(    tput sgr0   || tput me      ) # Reset cursor
       blink=$(    tput blink  || tput mb      ) # Start blinking
       italic=$(   tput sitm   || tput ZH      ) # Start italic
       eitalic=$(  tput ritm   || tput ZR      ) # End   italic
   [[ $TERM != *-m ]] && {
       red=$(      tput setaf 1|| tput AF 1    )
       green=$(    tput setaf 2|| tput AF 2    )
       yellow=$(   tput setaf 3|| tput AF 3    )
       blue=$(     tput setaf 4|| tput AF 4    )
       magenta=$(  tput setaf 5|| tput AF 5    )
       cyan=$(     tput setaf 6|| tput AF 6    )
   }
       white=$(    tput setaf 7|| tput AF 7    )
       default=$(  tput op                     )
       eed=$(      tput ed     || tput cd      )   # Erase to end of display
       eel=$(      tput el     || tput ce      )   # Erase to end of line
       ebl=$(      tput el1    || tput cb      )   # Erase to beginning of line
       ewl=$eel$ebl                                # Erase whole line
       draw=$(     tput -S <<< '   enacs
                                   smacs
                                   acsc
                                   rmacs' || { \
                   tput eA; tput as;
                   tput ac; tput ae;         } )   # Drawing characters
       back=$'\b'
   } 2>/dev/null ||:
}

fake_progress_bar() {
   while true; do
      ps -p $sleeppid_one $sleeppid_two $sleeppid_three $sleeppid_four $first_run_initializer_pid >/dev/null 2>&1
      if [ "$?" = "0" ]; then
         ## some pid is still running
         echo -n "."
         sleep 1 &
         wait "$!"
      else
         ## no pids running anymore
         echo ""
         break
      fi
   done
}

log_file="/var/lib/whonix-initializer/status-files/first_run_initializer.log"
start_file="/var/lib/whonix-initializer/status-files/first_run_initializer.start"
done_file="/var/lib/whonix-initializer/status-files/first_run_initializer.done"
done_file_compatiblity="/root/.whonix/first_run_initializer.done"
skip_file="/var/lib/whonix-initializer/status-files/first_run_initializer.skip"
todo_file="/var/lib/whonix-initializer/status-files/first_run_initializer.todo"
fail_file="/var/lib/whonix-initializer/status-files/first_run_initializer.fail"

## Check if a custom builder even had the verifiable builds option enabled,
## that may or may not have created the todo file.
if [ ! -f "$todo_file" ]; then
   true "($output_identifier) INFO: todo_file $todo_file does not exist. Exiting."
   exit 0
fi

## Check if a custom builder wants to skip this (for debugging purposes).
if [ -f "$skip_file" ]; then
   true "($output_identifier) INFO: skip_file $skip_file exist. Exiting."
   exit 0
fi

## Check if Whonix First Run Initializer already finished, exit if so.
if [ -f "$done_file" ]; then
   true "($output_identifier) INFO: done_file $done_file exist. Exiting."
   exit 0
fi
if [ -f "$done_file_compatiblity" ]; then
   true "($output_identifier) INFO: done_file_compatiblity $done_file_compatiblity exist. Exiting."
   exit 0
fi

## Extra precaution against this script getting automatically by dpkg after
## running apt-get. If the environment variable DPKG_MAINTSCRIPT_PACKAGE is
## set, then this script was started by apt-get -> dpkg -> invoke-rc.d.
## Unfortunately, works with sysvinit. Not with systemd.
## https://unix.stackexchange.com/questions/166450/preserve-environment-variables-using-systemd
if [ ! "$DPKG_MAINTSCRIPT_PACKAGE" = "" ]; then
   echo "($output_identifier) INFO $0: Run by package manager. Exiting. Ok."
   exit 0
fi

mkdir --parents "/var/lib/whonix-initializer/status-files/"

## Log, that Whonix First Run Initializer attempted to start. This is useful in
## eventual case of bug reports.
touch "$start_file"

## In case the done_file has been manually removed to re-run whonix-initializer
## (for debugging purposes or so), also delete the fail_file.
rm --force "$fail_file"

sync

colors

echo "\
($output_identifier) \
[${cyan}${bold}INFO${reset}] [${cyan}Whonix First Run Initializer${reset}]: Preparing Whonix... Will reboot when finished...
       ${cyan}${under}Do not interrupt this process or your system might be unstable!${reset}
       ${under}This may take a while...${reset}"

## The sleep is just in for the look an feel.
sleep 10 &
sleeppid_one="$!"

/usr/lib/first_run_initializer >> "$log_file" 2>&1 &
first_run_initializer_pid="$!"
fake_progress_bar
sync

wait "$first_run_initializer_pid"
first_run_initializer_exit_code="$?"

touch "$done_file"
rm --force "$todo_file"
sync

if [ "$first_run_initializer_exit_code" = "0" ]; then
   echo "($output_identifier) [${cyan}${bold}INFO${reset}] [${cyan}Whonix First Run Initializer${reset}]: Done. Rebooting... ${under}This may take a while...${eunder}"
else
   echo "\
($output_identifier) \
[${red}${bold}ERROR${reset}] [${cyan}Whonix First Run Initializer${reset}]: Error!
        ${under}Please report this Whonix bug! Submit Whonix First Run Initializer's${reset}
        ${under}log file $log_file to Whonix developers!${reset}
        Rebooting... ${under}This may take a while...${reset}"
   touch "$fail_file"
   echo "$first_run_initializer_exit_code" > "$fail_file"
fi

## The sleep is just in for the look an feel.
sleep 10 &
sleeppid_two="$!"
fake_progress_bar

reboot & disown

## The sleep is just in for the look an feel.
sleep 60 &
sleeppid_three="$!"
fake_progress_bar

echo "($output_identifier) [${red}${bold}ERROR${reset}] [${cyan}Whonix First Run Initializer${reset}]: Rebooting not done after 60 seconds. Please report this Whonix bug!"

## Sleep, so this message has a chance of being read.
sleep 10 &
sleeppid_four="$!"
fake_progress_bar

true "($output_identifier) INFO: End. Exiting."
exit 0
