#! /bin/bash
### BEGIN INIT INFO
# Provides:          whonix-initializer
# Required-Start:    $remote_fs $syslog mountkernfs
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# X-Interactive:     true
# Short-Description: whonix-initializer
# Description:       whonix-initializer
### END INIT INFO

## This file is part of Whonix.
## Copyright (C) 2012 - 2014 Patrick Schleizer <adrelanos@riseup.net>
## See the file COPYING for copying conditions.

#set -x

DESC="whonix-initializer"
NAME=whonix-initializer
SCRIPTNAME=/etc/init.d/$NAME
LOG=/var/log/$NAME.log

# Load the VERBOSE setting and other rcS variables
. /lib/init/vars.sh

# Define LSB log_* functions.
# Depend on lsb-base (>= 3.2-14) to ensure that this file is present
# and status_of_proc is working.
. /lib/lsb/init-functions

log() {
	echo "$@" >> "${LOG}"
}

do_start() {
	if [ -x /usr/lib/first_run_initializer_gui ]; then
		/usr/lib/first_run_initializer_gui
	fi
	return 0
}

do_stop() {
	return 0
}

do_status() {
	return 0
}

case "$1" in
  start)
	[ "$VERBOSE" != no ] && log_daemon_msg "$DESC" "$NAME"
	do_start
	case "$?" in
		0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
		2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
	esac
	;;
  stop)
	do_stop
	;;
  restart)
	do_stop
	do_start
	;;
  restartnd)
	do_stop
	do_start_nd
	;;
  force-reload)
	do_stop
	do_start
	;;
  status)
        do_status
        exit $?
	;;
  *)
	echo "Usage: $SCRIPTNAME (start|stop|restart|force-reload|status)" >&2
	exit 3
	;;
esac

:
